export const queryKeys = {
  authMe: ['auth', 'me'] as const,
  authProviders: ['auth', 'providers'] as const,
  servers: ['servers'] as const,
  tools: (opts?: { all?: boolean }) => ['tools', opts ?? {}] as const,
  groups: ['groups'] as const,
  group: (name: string) => ['group', name] as const,
  prompts: ['prompts'] as const,
  proxies: ['proxies'] as const,
  users: ['users'] as const,
  mcpClients: ['mcp-clients'] as const,
  myTokens: ['my-tokens'] as const,
  policies: ['policies'] as const,
  roles: ['roles'] as const,
  tenants: ['tenants'] as const,
  webhooks: ['webhooks'] as const,
  approvals: (status: string = 'pending') => ['approvals', status] as const,
  usage: (params: Record<string, string | number | undefined>) => ['usage', params] as const,
  audit: (params: Record<string, string | number | undefined>) => ['audit', params] as const,
  rateLimit: ['rate-limit'] as const,
  quota: ['quota'] as const,
  health: ['health'] as const,
  systemInfo: ['system', 'info'] as const,
};
